env:
  browser: true
  es2020: true
extends: 'eslint:recommended'
ignorePatterns:
  - gruntfile.js
  - doc
  - demos
  - dist
  - types
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
